---
- name: 'Create User on the remote server'
  user:
    name: "{{ item }}"
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
  with_items: "{{ users }}"
- name: 'Adding authorized keys'
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', 'files/{{ item }}_key.pub') }}"
  with_items: "{{ users }}"
